### ISSUE TITLE
`split1` methods use numerical values which aren't traditional in Rust naming conventions

### ISSUE THREAD

**Issue by eureka-cpu** [facebookincubator/gazebo#8]
Hello! Really excited to see that Facebook is contributing to the Rust ecosystem and surprised there isn't much activity here.

If this is intentional feel free to ignore me, just browsing through the code and saw this one nit. Should the methods that split at the first index of a string use '1' in their name (e.g `split1()`, `split1_opt()`) instead of `split_first()` or `split_start()`?

**Comment by ndmitchell** [comment]
The reason was that `split` gives you all the splits, `splitn` gives you the first N splits, so the logical name for the first 1 split is to substitute 1 for `n` and get `split1`. I appreciate it's not common in Rust functions, but in some ways you can see `splitn` as the thing that broke that first (since `n` in this context is a placeholder for a number). Certainly `split_first` would be a perfectly good name, although given that it already has a name, I'm not sure it's sufficiently better to justify changing it. That said, our hope is that eventually these functions end up in Rust proper - for example `split1_opt` is now in Rust as [`split_once`](https://doc.rust-lang.org/std/primitive.str.html#method.split_once) - so if they change name when moving over that seems perfectly fine.

**Comment by eureka-cpu** [comment]
Ah I understand, I'll go ahead and mark this closed then.

Thanks for the explanation!
